/**
 * The two generated `.d.ts` files that teach the language service about the host's world:
 * the context object (`row`) and the component library. Regenerated whenever the context
 * type or the library changes; both are registered as Monaco models so the Volar worker
 * type-checks against them.
 *
 * Two files, not one, because they need opposite shapes: augmenting `vue` requires a
 * *module* (hence the trailing `export {}`), while `import { useRow } from 'sprint'` needs
 * `sprint` to actually resolve — so it gets a real package under `/node_modules`.
 */

export const ENV_URI = 'file:///sprint-env.d.ts'
export const SPRINT_MODULE_URI = 'file:///node_modules/sprint/index.d.ts'
/** Library component sources live here so `typeof import(…)` picks up their `defineProps`. */
export const componentUri = (name: string) => `file:///sprint/${name}.vue`

/**
 * @param contextType TS type text for one record, e.g. the data source's `Row` type.
 * @param componentNames names of the library components available in every template.
 */
export function sprintEnv(contextType: string, componentNames: string[]): Record<string, string> {
  const globals = componentNames
    .map((name) => `    ${name}: typeof import('./sprint/${name}.vue').default`)
    .join('\n')

  return {
    [ENV_URI]: [
      '// Generated by @sprint/editor — the host\'s context type and component library.',
      `type Row = ${contextType}`,
      '',
      "declare module 'vue' {",
      '  // `row` is a template global (the runtime sets it as a global property).',
      '  interface ComponentCustomProperties { row: Row }',
      '  interface GlobalComponents {',
      globals,
      '  }',
      '}',
      '',
      'export {}',
      '',
    ].join('\n'),
    [SPRINT_MODULE_URI]: [
      '// Generated by @sprint/editor — the `sprint` module template scripts may import.',
      `export function useRow(): ${contextType}`,
      '',
    ].join('\n'),
  }
}
