/**
 * The two generated `.d.ts` files that teach the language service about the host's world:
 * the context object (`row`) and the component library. Regenerated whenever the context
 * type or the library changes; both are registered as Monaco models so the Volar worker
 * type-checks against them.
 *
 * Two files, not one, because they need opposite shapes: augmenting `vue` requires a
 * *module* (hence the trailing `export {}`), while `import { useRow } from 'pressed'` needs
 * `pressed` to actually resolve — so it gets a real package under `/node_modules`.
 */

export const ENV_URI = 'file:///pressed-env.d.ts'
export const SPRINT_MODULE_URI = 'file:///node_modules/pressed/index.d.ts'
/** Library component sources live here so `typeof import(…)` picks up their `defineProps`. */
export const componentUri = (name: string) => `file:///pressed/${name}.vue`

/**
 * @param contextType TS type text for one record, e.g. the data source's `Row` type.
 * @param componentNames names of the library components available in every template.
 * @param snippetNames the file's own `<snippet>` names — same deal, from the virtual models
 *   `snippets.ts` keeps in sync, so `<temp label="…">` is a known component with typed props.
 */
export function pressedEnv(contextType: string, componentNames: string[], snippetNames: string[] = []): Record<string, string> {
  const globals = [
    ...componentNames.map((name) => `    ${name}: typeof import('./pressed/${name}.vue').default`),
    ...snippetNames.map((name) => `    ${JSON.stringify(name)}: typeof import('./pressed/snippets/${name}.vue').default`),
  ].join('\n')

  return {
    [ENV_URI]: [
      '// Generated by @/editor — the host\'s context type and component library.',
      `type Row = ${contextType}`,
      '',
      "declare module 'vue' {",
      '  // `row` is a template global (the runtime sets it as a global property).',
      '  interface ComponentCustomProperties { row: Row }',
      '  interface GlobalComponents {',
      globals,
      '  }',
      '}',
      '',
      'export {}',
      '',
    ].join('\n'),
    [SPRINT_MODULE_URI]: [
      '// Generated by @/editor — the `pressed` module template scripts may import.',
      `export function useRow(): ${contextType}`,
      '',
    ].join('\n'),
  }
}
