import type { Icon, IconSet } from './types'

/**
 * Ours, hand-drawn: the marks a *label* needs and a general icon set does not draw. Same 24 grid as
 * Tabler, every shape in both of Tabler's dialects — `line` (2px round stroke, no fill) and
 * `fill` (one silhouette in currentColor, holes by even-odd). Bodies are already in sanitised
 * form: one `<path>`.
 *
 * GENERATED by scripts/pressed-icons.mjs — edit the geometry there, not here. docs/icons-pressed.md.
 */
const line = (name: string, d: string): Icon => ({
  name,
  viewBox: '0 0 24 24',
  body: `<path fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="${d}"/>`,
})
const fill = (name: string, d: string): Icon => ({
  name,
  viewBox: '0 0 24 24',
  body: `<path fill="currentColor" fill-rule="evenodd" d="${d}"/>`,
})

/** Screw drives, seen from above: the head is a ring (line) or a disc (fill), the recess inside r5. */
const DRIVES: Icon[] = [
  line('drive-slotted', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M7.5 12h9'),
  fill('drive-slotted-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M6 10.75h12v2.5h-12z'),
  line('drive-phillips', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M12 7.5v9M7.5 12h9'),
  fill('drive-phillips-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M10.75 6h2.5v4.75H18v2.5h-4.75V18h-2.5v-4.75H6v-2.5h4.75z'),
  line('drive-pozidriv', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M12 8v8M8 12h8M15.2 15.2l.9 .9M8.8 15.2l-.9 .9M8.8 8.8l-.9 -.9M15.2 8.8l.9 -.9'),
  fill('drive-pozidriv-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M10.75 6h2.5v4.75H18v2.5h-4.75V18h-2.5v-4.75H6v-2.5h4.75zM15.18 14.2L16.87 15.89L15.89 16.87L14.2 15.18zM9.8 15.18L8.11 16.87L7.13 15.89L8.82 14.2zM8.82 9.8L7.13 8.11L8.11 7.13L9.8 8.82zM14.2 8.82L15.89 7.13L16.87 8.11L15.18 9.8z'),
  line('drive-jis', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M12 7.5v9M7.5 12h9M9 15v.01'),
  fill('drive-jis-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M10.75 6h2.5v4.75H18v2.5h-4.75V18h-2.5v-4.75H6v-2.5h4.75zM7.5 15.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0'),
  line('drive-robertson', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M8.5 8.5h7v7h-7z'),
  fill('drive-robertson-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M8.5 8.5h7v7h-7z'),
  line('drive-hex', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M16.6 12L14.3 15.98L9.7 15.98L7.4 12L9.7 8.02L14.3 8.02z'),
  fill('drive-hex-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M17 12L14.5 16.33L9.5 16.33L7 12L9.5 7.67L14.5 7.67z'),
  line('drive-hex-pin', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M16.6 12L14.3 15.98L9.7 15.98L7.4 12L9.7 8.02L14.3 8.02zM12 12v.01'),
  fill('drive-hex-pin-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M17 12L14.5 16.33L9.5 16.33L7 12L9.5 7.67L14.5 7.67zM10.5 12a1.5 1.5 0 1 0 3 0a1.5 1.5 0 1 0 -3 0'),
  line('drive-torx', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M10.5 9.4L11.19 6.86Q12 6.1 12.81 6.86L13.5 9.4L16.04 8.73Q17.11 9.05 16.85 10.14L15 12L16.85 13.86Q17.11 14.95 16.04 15.27L13.5 14.6L12.81 17.14Q12 17.9 11.19 17.14L10.5 14.6L7.96 15.27Q6.89 14.95 7.15 13.86L9 12L7.15 10.14Q6.89 9.05 7.96 8.73z'),
  fill('drive-torx-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M10.5 9.4L11.19 6.86Q12 6.1 12.81 6.86L13.5 9.4L16.04 8.73Q17.11 9.05 16.85 10.14L15 12L16.85 13.86Q17.11 14.95 16.04 15.27L13.5 14.6L12.81 17.14Q12 17.9 11.19 17.14L10.5 14.6L7.96 15.27Q6.89 14.95 7.15 13.86L9 12L7.15 10.14Q6.89 9.05 7.96 8.73z'),
  line('drive-torx-pin', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M10.5 9.4L11.19 6.86Q12 6.1 12.81 6.86L13.5 9.4L16.04 8.73Q17.11 9.05 16.85 10.14L15 12L16.85 13.86Q17.11 14.95 16.04 15.27L13.5 14.6L12.81 17.14Q12 17.9 11.19 17.14L10.5 14.6L7.96 15.27Q6.89 14.95 7.15 13.86L9 12L7.15 10.14Q6.89 9.05 7.96 8.73zM12 12v.01'),
  fill('drive-torx-pin-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M10.5 9.4L11.19 6.86Q12 6.1 12.81 6.86L13.5 9.4L16.04 8.73Q17.11 9.05 16.85 10.14L15 12L16.85 13.86Q17.11 14.95 16.04 15.27L13.5 14.6L12.81 17.14Q12 17.9 11.19 17.14L10.5 14.6L7.96 15.27Q6.89 14.95 7.15 13.86L9 12L7.15 10.14Q6.89 9.05 7.96 8.73zM10.5 12a1.5 1.5 0 1 0 3 0a1.5 1.5 0 1 0 -3 0'),
  line('drive-spanner', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M8.5 12v.01M15.5 12v.01'),
  fill('drive-spanner-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M7 12a1.5 1.5 0 1 0 3 0a1.5 1.5 0 1 0 -3 0M14 12a1.5 1.5 0 1 0 3 0a1.5 1.5 0 1 0 -3 0'),
  line('drive-tri-wing', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M12 12v-5M12 12l-4.33 2.5M12 12l4.33 2.5'),
  fill('drive-tri-wing-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M10.8 6.5L13.2 6.5L13.2 11.31L17.36 13.71L16.16 15.79L12 13.39L7.84 15.79L6.64 13.71L10.8 11.31z'),
  line('drive-triangle', 'M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M12 7.2L16.16 14.4L7.84 14.4z'),
  fill('drive-triangle-filled', 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0 -20 0M12 6.8L16.5 14.6L7.5 14.6z'),
]

/** Screw heads, seen from the side: the head's silhouette above y 9 on the same 6-wide shank, pointed (wood) or flat (machine). */
const HEADS: Icon[] = [
  line('head-cap-wood', 'M7 9V5a2 2 0 0 1 2 -2h6a2 2 0 0 1 2 2v4M9 9v9l3 3l3 -3V9'),
  fill('head-cap-wood-filled', 'M7 9V4a2 2 0 0 1 2 -2h6a2 2 0 0 1 2 2v5H15v9l-3 4l-3 -4V9H7z'),
  line('head-cap-machine', 'M7 9V5a2 2 0 0 1 2 -2h6a2 2 0 0 1 2 2v4M9 9v12h6V9'),
  fill('head-cap-machine-filled', 'M7 9V4a2 2 0 0 1 2 -2h6a2 2 0 0 1 2 2v5H15v13H9V9H7z'),
  line('head-cheese-wood', 'M6 9V4h12v5M9 9v9l3 3l3 -3V9'),
  fill('head-cheese-wood-filled', 'M6 9V3h12v6H15v9l-3 4l-3 -4V9H6z'),
  line('head-cheese-machine', 'M6 9V4h12v5M9 9v12h6V9'),
  fill('head-cheese-machine-filled', 'M6 9V3h12v6H15v13H9V9H6z'),
  line('head-button-wood', 'M5 9a8.5 8.5 0 0 1 14 0M9 9v9l3 3l3 -3V9'),
  fill('head-button-wood-filled', 'M5 9a7.5 7.5 0 0 1 14 0H15v9l-3 4l-3 -4V9H5z'),
  line('head-button-machine', 'M5 9a8.5 8.5 0 0 1 14 0M9 9v12h6V9'),
  fill('head-button-machine-filled', 'M5 9a7.5 7.5 0 0 1 14 0H15v13H9V9H5z'),
  line('head-pan-wood', 'M5 9V6a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v3M9 9v9l3 3l3 -3V9'),
  fill('head-pan-wood-filled', 'M5 9V5a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v4H15v9l-3 4l-3 -4V9H5z'),
  line('head-pan-machine', 'M5 9V6a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v3M9 9v12h6V9'),
  fill('head-pan-machine-filled', 'M5 9V5a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v4H15v13H9V9H5z'),
  line('head-countersunk-wood', 'M9 9l-4 -5h14l-4 5M9 9v9l3 3l3 -3V9'),
  fill('head-countersunk-wood-filled', 'M9 9L5 4h14l-4 5H15v9l-3 4l-3 -4V9H9z'),
  line('head-countersunk-machine', 'M9 9l-4 -5h14l-4 5M9 9v12h6V9'),
  fill('head-countersunk-machine-filled', 'M9 9L5 4h14l-4 5H15v13H9V9H9z'),
  line('head-oval-wood', 'M9 9l-4 -5a10 10 0 0 1 14 0l-4 5M9 9v9l3 3l3 -3V9'),
  fill('head-oval-wood-filled', 'M9 9L5 5a11 11 0 0 1 14 0l-4 4H15v9l-3 4l-3 -4V9H9z'),
  line('head-oval-machine', 'M9 9l-4 -5a10 10 0 0 1 14 0l-4 5M9 9v12h6V9'),
  fill('head-oval-machine-filled', 'M9 9L5 5a11 11 0 0 1 14 0l-4 4H15v13H9V9H9z'),
  line('head-hex-wood', 'M5 9V4h14v5M12 4v5M9 9v9l3 3l3 -3V9'),
  fill('head-hex-wood-filled', 'M5 9V5l1 -1h12l1 1v4H15v9l-3 4l-3 -4V9H5z'),
  line('head-hex-machine', 'M5 9V4h14v5M12 4v5M9 9v12h6V9'),
  fill('head-hex-machine-filled', 'M5 9V5l1 -1h12l1 1v4H15v13H9V9H5z'),
  line('head-flange-wood', 'M8 9V3h8v6M12 3v6M4 9h16M9 9v9l3 3l3 -3V9'),
  fill('head-flange-wood-filled', 'M4 9V7.5h4V3h8v4.5h4V9H15v9l-3 4l-3 -4V9H4z'),
  line('head-flange-machine', 'M8 9V3h8v6M12 3v6M4 9h16M9 9v12h6V9'),
  fill('head-flange-machine-filled', 'M4 9V7.5h4V3h8v4.5h4V9H15v13H9V9H4z'),
  line('head-headless-wood', 'M9 9V5h6v4M9 9v9l3 3l3 -3V9'),
  fill('head-headless-wood-filled', 'M9 3h6v6H15v9l-3 4l-3 -4V9H9z'),
  line('head-headless-machine', 'M9 9V5h6v4M9 9v12h6V9'),
  fill('head-headless-machine-filled', 'M9 3h6v6H15v13H9V9H9z'),
]

const PRESSED: Icon[] = [...DRIVES, ...HEADS]

export const pressed: IconSet = { id: 'pressed', label: 'Pressed', load: async () => PRESSED }
